[project]
name = "workers-python"
version = "0.1.0"
description = "Cloudflare Workers Python Task Runner"
dependencies = [
    "redis",
    "mysql-connector-python",
    "fastapi",
    "uvicorn",
    "requests",
    "psutil"
]

readme = "README.md"
requires-python = ">=3.12"
